language: node_js
before_script:
  - npm install -g gulp
script: gulp default
node_js:
  - 24
  - 22
services:
  - mongodb
  - redis
env:
  global:
    - MONGODB_URL=mongodb://localhost/hangman
    - REDIS_URL=redis://localhost:6379/
