language: node_js
before_script:
  - npm install -g gulp
script: gulp default integration_test
node_js:
  - 14
  - 12
services:
  - mongodb
  - redis
env:
  global:
    - MONGODB_URL=mongodb://127.0.0.1:27017/hangman
    - REDIS_URL=redis://127.0.0.1:6397/
